version: '3'
services:
  web:
    build:
      context: https://${GITHUB_TOKEN}@github.com/cvmoretti/outlaw-motorsport-site.git
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always